> Interpreting GSEA results

# GSEA computes four key statistics for GSEA report:

1. Enrichment score (ES)
# primary result of GSEA is the enrichment score (ES) which reflects the degree to which a gene set is overrepresented at the top or bottom of a ranked list of genes. 
# GSEA calculates the ES by walking down the ranked list of genes, increasing a running-sum statistic when a gene is in the gene set and decreasing it when it is not. The magnitude of the increment depends on the correlation of the gene with the phenotype. The ES is the maximum deviation from zero encountered in walking the list. A positive ES indicates gene set enrichment at the top of the ranked list; a negative ES indicates a gene set enrichment at the bottom of the ranked list. 
# In the analysis results, the enrichment plot provides a graphical view of the ES for a gene set (i.e. "Enrichment plot: [GENE_SET]")
    # - top portion of the plot shows the running ES for the gene set as the analysis walks down the ranked list. The score at the peak of the plot (score furthest from 0.0) is the ES for the gene plot. Gene sets with a distinct peak at the beginning or end of the ranked list are generally the most interesting
    # - the middle portion of the plot shows where the members of the gene set appear in the ranked list of genes. The leading edge subset of a gene set is the subset of members that contribute most to the ES. For a positive ES (such as the one shown), the leading edge subset is the set of members that appear in the ranked list prior to the peak score. For a negative ES, it is the set of members that appear subsequent to the peak score.
    # - the bottom portion of the plot shows the value of the ranking metric as you move down the list of the ranked genes. The ranking metric measures a gene's correlation with a phenotype. The value of the ranking metric goes from positive to negative as you move down the ranked list. A positive value indicates correlation with the first phenotype and a negative value indicates correlation with the second phenotype. For continuous phenotypes (time series or gene of interest), a positive value indicates correlation with the phenotype profile and a negative value indicates no correlation or inverse correlation with the profile

2. Normalized enrichment score (NES)
# The normalized ES (NES) is the primary statistic for examining gene set enrichment results. By normalizing the ES, GSEA accounts for differences in gene set size and in correlations between gene sets and the expression dataset; therefore, the NES can be used to compare analysis results across gene sets. GSEA determines GSEA as follows:

# NES = actual ES / mean(ESs against the permutations of the dataset)

# Since the NES is based on GSE scores for all dataset permutations, changing the permutation method, # of permutations, or size of expression dataset affects the NES. For example, let's compare two analyses:

    # (1): you analyze an expression dataset, GSEA generates a ranked list and analyzes the ranked list
    # (2): you use GSEAPreranked to analyze the ranked list generated by the first analysis

# If you use the same parameter settings, your enrichment scores are identical; however, the NESs reflect the very different datasets (the expression dataset vs. the ranked list of genes) used for the permutations

3. False discovery rate (FDR)

# FDR is the estimated probability that a gene set with a given NES represents a false positive finding. For example, an FDR of 25% indicates that the result is likely to be valid 3 out of 4 times. The GSEA analysis report highlights enrichment gene sets with an FDR of < 25%  as those most likely generate interesting hypotheses and driver further research, but provides analysis results for all analyzed gene sets. In general, given the lack of coherence in most expression datasets nad the relatively small number of gene sets being analyzed, an FDR cutoff of 25% is appropriate. However, if you have a small number of samples and use gene_set permutation (rather than phenotype permutation) for your analysis, you are using a less stringent assessment of significance and would then want to use a more stringent FDR cutoff, such as 5%.

# The FDR is a ratio of two distributions: (1) the actual ES vs. the ES for all gene sets against all permutations of the dataset, and (2) the actual ES vs. the ES of all genesets against the actual dataset. 

# In general, the larger the absolute NES the smaller the FDR; that is, as the absolute NES decreases the corresponding FDR increases. However, because the distribution curves tend to be 'bumpy' at the tails, you may notice exceptions to this in your GSEA results. For similar reasons, although FDR is less conservative than FWER, you may notice instances in the GSEA results where the FWER is less than FDR. 

4. Nominal p-value

# The nominal p value estimates the statistical significance of the ES for a single gene set. However, when you are evaluating multiple gene sets, you must correct for gene set size and multiple hypothesis testing. Because the p value is not adjusted for either, it is of limited value when comparing gene sets. The GSEA PNAS paper describes the p value statistic in the section titled "Appendix: Mathematical Description of Methods". 

# The FDR is adjusted for gene set size and multiple hypotheses testing while the p value is not. When a top gene set has a small nominal p value and a high FDR value, it generally indcates that it is not as significant when compared with other gene sets in the empirical null distribution. this could be because you do not have enough samples, the biological signal is subtle, or the gene sets do not represent the biology in question very well. On the other hand, the FDR is based on two distributions of all gene sets; if only one of many gene sets is enriched, that gene set is likely to have a high FDR. Finally, a top gene set with a high nominal p value and a low FDR value, generally indicates a negative result: the gene set itself is not significant and other sets are weaker. 

# In the GSEA report, a p value of zero (0.0) indicates an actual p value of less than 1/number-of-permutations. For example, if the analysis performed 100 permutations, a reported value of 0.0 indicates an actual p value of less than 0.001. For a more accurate p-value, increase the number of permutations performed by the analysis. Typically, you will want to perform 1000 permutations (phenotype or gene_set). If you attempt to perform more than 1000 permutations, GSEA may run out of memory. 

> GSEA report

1. Enrichment in phenotype

# Each report contains two "enrichment in phenotype" sections. The first section shows results for gene sets that have a positive ES (gene sets that show enrichment at the top of the ranked list) and second section shows results for gene sets that have a negative ES (gene sets that show enrichment at the bottom of the ranked list). For categorical phenotypes, a positive ES indicates correlation with the first phenotype and a negative ES indicates correlation with second phenotype. For continuous phenotypes (time series or GOI), a positive value indicates correlation with the phenotype profile and negative value indicates no correlation or inverse correlation with the phenotype profile.

2. Dataset details

3. Gene set details

4. Gene markers

5. Global statistics and plots

6. Other

7. Detailed enrichment results

8. Gene set details report
